services:
  app:
    build:
      context: ./back
    container_name: laravel_app
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel_db
      - DB_USERNAME=root
      - DB_PASSWORD=root

  vue:
    image: node:18
    ports:
      - "8080:8080"
    volumes:
      - ./front:/app
    working_dir: /app
    command: /bin/bash -c "npm install && npm run dev"

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db


  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    depends_on:
      - mysql

networks:
  default:
    driver: bridge
